
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.0'

dependencies:
    - OpenZeppelin/openzeppelin-contracts@4.3.0

dotenv: .env

wallets:
  from_key: ${TEST_PRIVATE_KEY}


igo_token_params:
  name: 'Cosmic IGO'
  symbol: 'COSMICIGO'
  decimals: 1
  multisig_test_address: ${TEST_MULTISIG_ADDRESS}



