
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.0'

dependencies:
    - OpenZeppelin/openzeppelin-contracts@4.3.0

dotenv: .env

test_wallets:
  from_key: ${TEST_PRIVATE_KEY}

wallets:
  from_key: ${MAINNET_PRIVATE_KEY}


igo_token_params:
  name: 'Cosmic IGO'
  symbol: 'COSMICIGO'
  price_numerator: 3
  price_denominator: 10
  max_amount: 12500000000000000000000000
  max_presale_mint: 2500000000000000000000000
  multisig_test_address: ${TEST_MULTISIG_ADDRESS}
  multisig_mainnet_address: ${MAINNET_MULTISIG_ADDRESS}

payment_coin_params:
  address: '0x...'


